version: 4.0.0.{build}
clone_folder: c:\projects\nlog
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '4.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '4.0'
nuget:
  project_feed: true
before_build:
  - ps: nuget restore -DisableParallelProcessing
matrix:
  fast_finish: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: quiet
deploy: off
after_test:
  - nuget.exe install OpenCover -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"\"c:\projects\nlog\NLog.ManualFlush.Tests\bin\Release\NLog.ManualFlush.Tests.dll\" -appveyor -noshadow"  -returntargetcode -filter:"+[NLog.ManualFlush]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
 
